### ISSUE TITLE
[CI]: add lighthouse CI in travis

### ISSUE THREAD

**Issue by anikethsaha** [anikethsaha/MERN-Boilerplate#125]
Lighthouse can be added in our `travis` config in order to keep up with the bundle 's quality

**Helpful links**

- [lighthouse repo](https://github.com/GoogleChrome/lighthouse-ci)
- [Usage with `.travis.yml`](https://github.com/GoogleChrome/lighthouse-ci#quick-start)
- [`lighthouse commands`](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/cli.md)
- [Lighthouse GH app](https://github.com/apps/lighthouse-ci)

**Comment by jeffin143** [comment]
@anikethsaha , I would like to take this up, can you assign me. I will take a look today :)

**Comment by jeffin143** [comment]
Let me know if the following makes sense

Expose the server using ngrok and then run lighthouse against that custom build URL, which gets expired after 8 hours , or we could stop the server too 

whatsoever looks feasible

**Comment by anikethsaha** [comment]
I guess it can be done by running `client: start` in the script and then test the link it's giving?

> Expose the server using ngrok and then run lighthouse against that custom build URL,

Lets try this :

> or we could stop the server too

I guess closing is much better any way we are not getting many PR so it won't harm any but still 👌

**Comment by anikethsaha** [comment]
https://github.com/anikethsaha/mern/pull/129
