### ISSUE TITLE
refacore: Move all webpack.*.js to .webpack folder

### ISSUE THREAD

**Issue by anikethsaha** [anikethsaha/MERN-Boilerplate#133]
This is cleaner to have `.webpack` or `webpack` folder where all the webpack configs will live. Need to change npm scripts too

**Comment by JeremiahKamama** [comment]
May I tackle this?

**Comment by anikethsaha** [comment]
sure 👍

**Comment by Ckbhatia** [comment]
@anikethsaha 
Is this issue work in progress or still no one picked?

**Comment by anikethsaha** [comment]
No one picked as of now. Feel free to take it

**Comment by ghost** [comment]
Hi! is this issue opened ?

**Comment by ghost** [comment]
Can I join to this task and contribute with someone more? This will be my first contribution.

**Comment by Ckbhatia** [comment]
Hi, this issue has been fixed now.
