### ISSUE TITLE
Trying to test

### ISSUE THREAD

**Issue by procarrera** [anikethsaha/MERN-Boilerplate#142]
Hi guys, i am trying to reproduce the Getting Started guide but didnt succeed

I cloned and installed all dependencies by: `npm install`
then, in the root folder: mern/  i run: `~/mern$ npm run server:dev`

but i am getting this error:

```
> MERN@1.0.0 server:dev /home/pedro/Desktop/Web/e-commerce/mern
> nodemon NODE_ENV=development --inspect bin/server.js

  Usage: nodemon [nodemon options] [script.js] [args]

  See "nodemon --help" for more.
```

There is any thing i am doing wrong?

**Comment by anikethsaha** [comment]
hi, thanks for the issue, 
`nodemon` did some breaking release since I last worked on this project. 
Could you try downgrading your `nodemon` version, maybe to `1.19.4`.

**Comment by procarrera** [comment]
hello @anikethsaha , i will try downgrading it and let you know asap.

thanks!
