### ISSUE TITLE
Fix CI failing errors

### ISSUE THREAD

**Issue by anikethsaha** [anikethsaha/MERN-Boilerplate#22]
## Updated

Currently, there are few scripts and steps failing in CI. Those fixes can be simple. 

---
The Build pipeline is important for project development and production.

The tool to use for this : [Travis CI](https://travis-ci.org)

example for similar config file I am looking: 
`.travis.yml` : 
```bash
language: node_js
node_js:
    - "10"
    - "8"
    - "6"
cache:
    directories:
        - ~/.npm
script: 
        - npm run test 
        - npm run lint
```

Please add better scripts here and in `package.json` to make it more feasible and smooth.
Thanks

**Comment by anikethsaha** [comment]
done at https://github.com/anikethsaha/MERN-Boilerplate/commit/9f7023871acceaa5c8482e2328a1cd02d4aaa030

**Comment by anikethsaha** [comment]
Reopening for fixing status

**Comment by lexcorp16** [comment]
Hi @anikethsaha Can you point me in the right direction on what needs to be done. Thanks

**Comment by anikethsaha** [comment]
@lexcorp16 You can check the logs here https://travis-ci.org/anikethsaha/MERN-Boilerplate/builds/578456436
There are only linting issues so you can get the help of automatic linting fixing commands or even vscode can help with this.
